# Generated by Django 3.2.4 on 2021-06-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_poll_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='texto',
        ),
    ]
