# Generated by Django 3.2.4 on 2021-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_cuestion2_cuestion3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cuestion1',
        ),
        migrations.DeleteModel(
            name='Cuestion2',
        ),
        migrations.DeleteModel(
            name='Cuestion3',
        ),
    ]
